### ISSUE TITLE
No such file bug on rust-lang/rust

### ISSUE THREAD

**Issue by pickfire** [drahnr/cargo-spellcheck#77]
**Describe the bug**

It errors but the error should be incorrect.

**To Reproduce**
Steps to reproduce the behaviour:
1. `git clone https://github.com/rust-lang/rust`
2. `cd rust`
3. `cargo spellcheck`
4. `Error: Failed to parse manifest file /home/ivan/src/pickfire/rs/rust/src/bootstrap/Cargo.toml: No such file or directory (os error 2)`
5. File actually does exists, `ls` does show the file. Content:
```toml
[package]
authors = ["The Rust Project Developers"]
name = "bootstrap"
version = "0.0.0"
edition = "2018"

[lib]
name = "bootstrap"
path = "lib.rs"
doctest = false

[[bin]]
name = "bootstrap"
path = "bin/main.rs"
test = false

[[bin]]
name = "rustc"
path = "bin/rustc.rs"
test = false

[[bin]]
name = "rustdoc"
path = "bin/rustdoc.rs"
test = false

[[bin]]
name = "sccache-plus-cl"
path = "bin/sccache-plus-cl.rs"
test = false

[[bin]]
name = "llvm-config-wrapper"
path = "bin/llvm-config-wrapper.rs"
test = false

[dependencies]
build_helper = { path = "../build_helper" }
cmake = "0.1.38"
filetime = "0.2"
num_cpus = "1.0"
getopts = "0.2.19"
cc = "1.0.35"
libc = "0.2"
serde = { version = "1.0.8", features = ["derive"] }
serde_json = "1.0.2"
toml = "0.5"
lazy_static = "1.3.0"
time = "0.1"
ignore = "0.4.10"
opener = "0.4"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
features = ["fileapi", "ioapiset", "jobapi2", "handleapi", "winioctl"]

[dev-dependencies]
pretty_assertions = "0.6"
```
It is quite long but it also does not work for other directories as well.

**Expected behavior**

I don't know, it should check something.

**Screenshots**

```
> cargo spellcheck
Error: Failed to parse manifest file /home/ivan/src/pickfire/rs/rust/src/bootstrap/Cargo.toml: No such file or directory (os error 2)
```

**Pplease complete the following information:**
 - System: Arch Linux - Linux arch 5.7.10-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 22 Jul 2020 20:13:40 +0000 x86_64 GNU/Linux
 - Obtained: `cargo install --git https://github.com/drahnr/cargo-spellcheck cargo-spellcheck`
 - Version: `0.3.0-alpha.6`

**Additional context**

Reference https://github.com/rust-lang/rust/issues/74697#issuecomment-663500345
